name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  setup:
    name: 'Setup'
    runs-on: ubuntu-latest
    steps:
      - uses: wyvox/action@add-turborepo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: wyvox/action@add-turborepo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm lint


  test:
    name: "Default Tests"
    runs-on: ubuntu-latest
    needs: [setup]

    steps:
      - uses: wyvox/action@add-turborepo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm test

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: wyvox/action@add-turborepo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pnpm-args: --no-lockfile
      - run: pnpm test

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: [test]

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-4.8
          - ember-lts-4.12
          - ember-5.0
          - ember-release
          - ember-beta
          - ember-canary
          - embroider-safe
          - embroider-optimized

    steps:
      - uses: wyvox/action@add-turborepo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tests
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
        working-directory: test-app

  typecheck:
    name: '${{ matrix.typescript-scenario }}'
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: [test]
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        typescript-scenario:
          - typescript@4.8
          - typescript@4.9
          - typescript@5.0
          - typescript@rc
          - typescript@next

    steps:
      - uses: wyvox/action@add-turborepo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Change TS to ${{ matrix.typescript-scenario }}'
        run: 'pnpm add --save-dev ${{ matrix.typescript-scenario}}'
        working-directory: ./test-app
      - name: 'Type checking'
        run: |
          pnpm --filter "test-app*" exec tsc -v;
          pnpm --filter "test-app*" exec glint --version;
          pnpm --filter "test-app*" exec glint;

  # https://github.com/changesets/action
  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [typecheck, try-scenarios]
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: wyvox/action@add-turborepo
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          title: "Release Preview"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}



